# 
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— 
# â–ˆâ–ˆâ•”â•â•â•â•â•â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•
# â•šâ•â•â•â•â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â• 
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘     
# â•šâ•â•â•â•â•â•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•šâ•â•     
#                                                             

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fossil_branch\
$hg_branch\
${custom.syncthing}\
$fill\
$sudo\
$all\
$status\
$cmd_duration\
$battery\
$time\
$line_break\
$character
"""

# right_format = """$status\
# $cmd_duration"""

continuation_prompt = "[Â» ](dimmed)"
command_timeout = 1000

[username]
style_user = 'bold purple'
style_root = 'bold red'
format = '[î·…]($style) [$user]($style) in '

[character]
format = "$symbol "
success_symbol = '[ï…¸ ](bold green)'
error_symbol = '[ï…¸ ](bold red)'

[directory]
style = 'bold cyan'
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = true
read_only = ' ï€£'
read_only_style = 'bold cyan'
home_symbol = '~'
repo_root_format = '[$path]($style)[$read_only]($read_only_style)[ï„¦ ](bold yellow)'
# home_symbol = 'ï€• '
# fish_style_pwd_dir_length = 1

[directory.substitutions]
# 'ï€• /.config' = 'ï€“ '
# 'ï€• /Desktop' = 'ï„ˆ '
# 'ï€• /Documents' = 'ï€­ '
# 'ï€• /Downloads' = 'ï€™ '
# 'ï€• /Galaxy' = 'ï…» '
# 'ï€• /Music' = 'ï€¥ '
# 'ï€• /Pictures' = 'ï€¾ '
# 'ï€• /Public' = 'ï« '
# 'ï€• /Scripts' = 'ï„  '
# 'ï€• /Templates' = 'ïƒ… '
# 'ï€• /Videos' = 'ï€½ '
# 'ï€• /Wallpapers' = 'î¹² '

[fill]
disabled = false
symbol = ' '

[cmd_duration]
min_time = 2000
format = ' [ï„‚](italic) [$duration](bold yellow)' 

[sudo]
disabled = false
symbol = 'ï‚„' 
format = ' [$symbol]($style) '
style = 'bold yellow'

[jobs]
format = " [$symbol $number]($style)"
style = "white"
symbol = "[âœ¦](cyan bold)"

[battery]
format = " $symbol [$percentage]($style)"
full_symbol = "ó°¹"
charging_symbol = "[ó°‚„](green)"
discharging_symbol = "ó°¿"
unknown_symbol = "ó°‚ƒ"
empty_symbol = "ó°‚"

[[battery.display]]
threshold = 25
style = "red"
discharging_symbol = "ó°»"

[[battery.display]]
threshold = 50
style = "yellow"

[status]
disabled = false
format = ' $symbol [$status]($style)'
style = 'bold bright-red'
success_style = 'bold bright-green'
symbol = "ï€"
not_executable_symbol = "ï"
not_found_symbol = "ï€‚"
sigint_symbol = "ïƒ§"
signal_symbol = "ïƒ§"
map_symbol = true
pipestatus = true
pipestatus_separator = ' |'
pipestatus_format = '\[$pipestatus\] => $symbol [$status]($style)'

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed"

# 
# â”Œâ”€â”â”¬ â”¬â”Œâ”¬â”â”Œâ” â”Œâ”€â”â”¬  â”Œâ”€â”
# â””â”€â”â””â”¬â”˜â”‚â”‚â”‚â”œâ”´â”â”‚ â”‚â”‚  â””â”€â”
# â””â”€â”˜ â”´ â”´ â”´â””â”€â”˜â””â”€â”˜â”´â”€â”˜â””â”€â”˜
#

[aws]
symbol = "ïƒ‚"
format = " $symbol [$profile $region]($style)"
style = "bold yellow"

[buf]
symbol = "ï’"
format = " $symbol [$version]($style)"
style = "bold cyan"
detect_files = ['buf.yaml', 'buf.gen.yaml', 'buf.work.yaml']

[c]
symbol = "î˜"
format = " $symbol [$version]($style)"
style = "bold blue"
detect_extensions = ['c', 'h']

[cpp]
symbol = "î˜"
format = " $symbol [$version]($style)"
style = "bold blue"
detect_extensions = ['cpp', 'cc', 'cxx', 'c++', 'hpp', 'hh', 'hxx', 'h++', 'tcc']

[cmake]
symbol = "î”"
format = " $symbol [$version]($style)"
style = "bold red"
detect_files = ['CMakeLists.txt', 'CMakeCache.txt']

[conda]
symbol = "ï„Œ"
format = " $symbol [$environment]($style)"
style = "bold green"
truncation_length = 1
ignore_base = true
detect_env_vars = ["!PIXI_ENVIRONMENT_NAME"]

[crystal]
symbol = "î˜¯"
format = " $symbol [$version]($style)"
style = "bold bright-black"
detect_extensions = ['cr']
detect_files = ['shard.yml']

[dart]
symbol = "î™Œ"
format = " $symbol [$version]($style)"
style = "bold cyan"
detect_extensions = ['dart']
detect_files = ['pubspec.yaml', 'pubspec.yml', 'pubspec.lock']
detect_folders = ['.dart_tool']

[docker_context]
symbol = "î™"
format = " $symbol [$context]($style)"
style = "bold cyan"
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

[elixir]
symbol = "î˜­"
format = " $symbol [$version (OTP $otp_version)]($style)"
style = "bold purple"
detect_files = ['mix.exs']

[elm]
symbol = "î˜¬"
format = " $symbol [$version]($style)"
style = "bold green"
detect_extensions = ['elm']
detect_files = ['elm.json', 'elm-package.json', '.elm-version']
detect_folders = ['elm-stuff']

[fennel]
symbol = "îš¯"
format = " $symbol [$version]($style)"
style = "bold yellow"
detect_extensions = ['fnl']

[fossil_branch]
symbol = "ï˜ "
style = "bold yellow"

[git_branch]
symbol = "ï˜ "
style = 'bold yellow'

[git_commit]
tag_symbol = 'ï€«'
format = " $symbol [($hash$tag)]($style)"
style = "bold green"
only_detached = true
tag_disabled = false
commit_hash_length = 3

[git_status]
style = 'bold yellow'
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead = "â†‘"
behind = "â†“"
diverged = "ğŸ¡™"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "Ã—"

[golang]
symbol = "î˜§"
format = " $symbol [$version]($style)"
style = "bold cyan"
not_capable_style = 'bold red'
detect_extensions = ['go']
detect_files = ['go.mod', 'go.sum', 'go.work', 'glide.yaml', 'Gopkg.yml', 'Gopkg.lock', '.go-version']
detect_folders = ['Godeps']

[guix_shell]
symbol = "ïŒ¥"
format = " $symbol [$version]($style)"
style = "bold yellow"

[haskell]
symbol = "î˜Ÿ"
format = " $symbol [$version]($style)"
style = "bold purple"
detect_extensions = ['hs', 'cabal', 'hs-boot']
detect_files = ['stack.yaml', 'cabal.project']

[haxe]
symbol = "î™¦"
format = " $symbol [$version]($style)"
style = "bold yellow"
detect_extensions = ['hx', 'hxml']
detect_files = ['project.xml', 'Project.xml', 'application.xml', 'haxelib.json', 'hxformat.json', '.haxerc']
detect_folders = ['.haxelib', 'haxe_libraries']

[hg_branch]
symbol = "ï˜ "
style = "bold yellow"

[hostname]
ssh_symbol = "î¹†"
format = "[$ssh_symbol $hostname]($style) in "
ssh_only = true
style = "bold purple"
trim_at = "."

[java]
symbol = "î‰–"
format = " $symbol [$version]($style)"
style = "bold bright-red"
detect_extensions = ['java', 'class', 'gradle', 'jar', 'cljs', 'cljc']
detect_files = ['pom.xml', 'build.gradle.kts', 'build.sbt', '.java-version', 'deps.edn', 'project.clj', 'build.boot', '.sdkmanrc']

[julia]
symbol = "î˜¤"
format = " $symbol [$version]($style)"
style = "bold purple"
detect_extensions = ['jl']
detect_files = ['Project.toml', 'Manifest.toml']

[kotlin]
symbol = "î˜´"
format = " $symbol [$version]($style)"
style = "bold purple"
detect_extensions = ['kt', 'kts']
kotlin_binary = "kotlin"

[lua]
symbol = "î˜ "
format = " $symbol [$version]($style)"
style = 'bold blue'
detect_extensions = ['lua']
detect_files = ['.lua-version']
detect_folders = ['lua']
lua_binary = 'lua'

[memory_usage]
disabled = false
symbol = "î¿…"
format = " [ï±](bold yellow)  $symbol  [ram ${ram_pct} | swp ${swap_pct}]($style)"
style = "bold red"
threshold = 75

[meson]
symbol = "ó°”·"
format = " $symbol [$project]($style)"
style = "bold purple"
truncation_symbol = ''

[nim]
symbol = "î™·"
format = " $symbol [$version]($style)"
style = "bold yellow"
detect_extensions = ['nim', 'nims', 'nimble']
detect_files = ['nim.cfg']

[nix_shell]
symbol = "ïŒ“"
format = " $symbol [$state($name)]($style) "
style = "bold cyan"

[nodejs]
symbol = "îœ˜"
format = " $symbol [$version]($style)"
style = 'bold green'
detect_extensions = ['js', 'mjs', 'cjs', 'ts', 'mts', 'cts']
detect_files = ['package.json', '.node-version', '.nvmrc']
detect_folders = ['node_modules']

[ocaml]
symbol = "î™º"
format = " $symbol [$version ($switch_indicator$switch_name)]($style)"
style = "bold yellow"
global_switch_indicator = ''
local_switch_indicator = '*'
detect_extensions = ['opam', 'ml', 'mli', 're', 'rei']
detect_files = ['dune', 'dune-project', 'jbuild', 'jbuild-ignore', '.merlin']
detect_folders = ['_opam', 'esy.lock']

[package]
symbol = "ó°—"
format = " [$symbol] [$version]($style)"
style = "bold yellow"
display_private = false

[perl]
symbol = "î™¾"
format = " $symbol [$version]($style)"
style = "bold cyan"
detect_extensions = ['pl', 'pm', 'pod']
detect_files = ['Makefile.PL', 'Build.PL', 'cpanfile', 'cpanfile.snapshot', 'META.json', 'META.yml', '.perl-version']

[php]
symbol = "î˜ˆ"
format = " $symbol [$version]($style)"
style = "bold purple"
detect_extensions = ['php']
detect_files = ['composer.json', '.php-version']

[pijul_channel]
symbol = "ï˜ "
style = "bold yellow"

[python]
symbol = "î˜†"
format = " $symbol [$version]($style)"
style = 'bold yellow'
python_binary = ['python', 'python3', 'python2']
detect_extensions = ["py", "ipynb"]
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']

[rlang]
symbol = "îšŠ"
format = " $symbol [$version]($style)"
style = "bold blue"
detect_extensions = ['R', 'Rd', 'Rmd', 'Rproj', 'Rsx']
detect_files = ['.Rprofile']
detect_folders = ['.Rproj.user']

[ruby]
symbol = "î‘"
format = " $symbol [$version]($style)"
style = "bold red"
detect_extensions = ['rb']
detect_files = ['Gemfile', '.ruby-version']
detect_variables = ['RUBY_VERSION', 'RBENV_VERSION']

[rust]
symbol = "îš‹"
format = " $symbol [$version]($style)"
style = "bold red"
detect_extensions = ['rs']
detect_files = ['Cargo.toml']

[scala]
symbol = "îš"
format = " $symbol [$version]($style)"
style = "bold red"
detect_extensions = ['sbt', 'scala']
detect_files = ['.scalaenv', '.sbtenv', 'build.sbt']
detect_folders = ['.metals']

[swift]
symbol = "îš™"
format = " $symbol [$version]($style)"
style = "bold yellow"
detect_extensions = ['swift']
detect_files = ['Package.swift']

[zig]
symbol = "îš©"
format = " $symbol [$version]($style)"
style = "bold yellow"
detect_extensions = ['zig']

[gradle]
symbol = "î™ "
format = " $symbol [$version]($style)"
style = "bold green"
detect_extensions = ['gradle', 'gradle.kts']
detect_folders = ['gradle']

[custom.syncthing]
symbol = "ï‘ª"
style = "bold yellow"
detect_folders = [".stfolder"]
format = " [$symbol]($style)"
